version: '3.1'
services:
  database:
    container_name: investorx_database
    image: postgres:9.6.3-alpine
    ports:
      - 5432:5432
  backend:
    container_name: investorx_backend
    depends_on:
      - database
    build: ./backend
    volumes:
      - ./backend:/opt/app:cached
    entrypoint: ["yarn", "dev"]
    ports:
      - 8080:8080
  frontend:
    container_name: investorx_frontend
    build: ./frontend
    volumes:
      - ./frontend:/opt/app:cached
    entrypoint: ["yarn", "dev"]
    ports:
      - 3000:3000
