query deal($shortId: ID!) {
  deal(shortId: $shortId) {
    id
    shortId
    company {
      id
      name
      domain
    }
    category {
      id
      name
    }
    name
    spvName
    roundSize {
      amount
      currency
    }
    premoneyValuation {
      amount
      currency
    }
    amountAllocatedToOrganization {
      amount
      currency
    }
    minTicket {
      amount
      currency
    }
    maxTicket {
      amount
      currency
    }
    referenceClosingDate
    carried
    hurdle
    deck {
      name
      url
      image
      uploaded
    }
    ticketsSum {
      count
      sum {
        amount
        currency
      }
    }
    investors {
      id
      fullName
      picture {
        url
      }
      ticketsSum {
        count
      }
    }
    tickets {
      id
      investor {
        fullName
        picture {
          url
        }
      }
      amount {
        amount
        currency
      }
    }
  }
}
