query {
  tickets {
    id
    investor {
      id
      fullName
      email
      picture {
        url
      }
    }
    deal {
      id
      company {
        name
        website
        description
        domain
      }
      category {
        name
      }
      name
      amountAllocatedToOrganization {
        amount
        currency
      }
      roundSize {
        amount
        currency
      }
    }
    amount {
      amount
      currency
    }
    status
    createdAt
  }
}
